# Generated by Django 3.1.3 on 2021-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20211006_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
