# Generated by Django 3.1.3 on 2021-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_detective',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xa07cceaa1bf0d88bf5037c005d542ca9', max_length=128),
        ),
    ]
