# Generated by Django 3.1.3 on 2021-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xebf5ce4f491cea09a7987942ee7667f6', max_length=128),
        ),
    ]
