# Generated by Django 3.1.3 on 2021-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211006_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xdef39df300e9ab38ae415e7a544b6fb5', max_length=128),
        ),
    ]
