# Generated by Django 3.1.3 on 2021-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211006_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xc910714f2da4d070a6231e0dd335173', max_length=128),
        ),
    ]
