# Generated by Django 3.1.3 on 2021-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211006_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x1e019846bc880dc41ce5e39c476192c0', max_length=128),
        ),
    ]
