# Generated by Django 3.1.3 on 2021-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211008_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4f660c15062452df480979de9b40393', max_length=128),
        ),
    ]
